#!/bin/bash

TEST_NAME="sig"
TEST_TOPOLOGY="topology/Tiny.topo"

test_setup() {
    set -e
    ./scion.sh topology zkclean -c $TEST_TOPOLOGY -d --sig -n 242.0.0.0/16

    # ./docker.sh base
    # ./docker.sh build
    # make -C docker/perapp base
    # docker build -f acceptance/sig_acceptance/Dockerfile.sig -t scion_sig_acceptance acceptance/sig_acceptance
    # docker build -f acceptance/sig_acceptance/Dockerfile.tester -t scion_sig_tester acceptance/sig_acceptance

    ./tools/dc init
    ./scion.sh start
    # Start sigs
    ./tools/dc sig up -d
    # Start testing containers
    ./tools/dc tester up -d
}

test_ping() {
    set -e
    # Run ping
    ./bin/ping_sigintegration -d
}

test_iperf() {
    set -e
    # Run iperf
    ./bin/sig_iperf_integration
}

test_teardown() {
    set -e
    ./tools/dc down
}

print_help() {
    echo
	cat <<-_EOF
	    $PROGRAM name
	        return the name of this test
	    $PROGRAM setup
	        execute only the setup phase.
	    $PROGRAM ping
	        execute only the ping phase.
	    $PROGRAM iperf
	        execute only the iperf phase.
	    $PROGRAM teardown 
	        execute only the teardown phase.
	_EOF
}

PROGRAM=`basename "$0"`
COMMAND="$1"

case "$COMMAND" in
    name)
        echo $TEST_NAME ;;
    setup|ping|iperf|teardown)
        "test_$COMMAND" ;;
    *) print_help; exit 1 ;;
esac

